spring:
  application:
    name: bookMS

  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 8081